name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

categories:
  - title: 'ðŸš€ New Features'
    collapse-after: 5
    labels:
      - 'type:feature'
      - 'type:style'
      - 'type:test'
  - title: 'ðŸž Bugs Fixes'
    collapse-after: 5
    labels:
      - 'type:bugfix'
  - title: 'ðŸ“š Documentation'
    collapse-after: 5
    labels:
      - 'type:docs'
  - title: 'ðŸ§° Maintenance'
    collapse-after: 5
    labels:
      - 'type:refactor'
      - 'type:perf'
  - title: 'ðŸ›  Configuration'
    collapse-after: 5
    labels:
      - 'type:config'
      - 'type:build'
      - 'type:ci'

version-resolver:
  major:
    labels:
      - 'type:major'
  minor:
    labels:
      - 'type:feature'
      - 'type:style'
      - 'type:docs'
      - 'type:perf'
  patch:
    labels:
      - 'type:bugfix'
      - 'type:build'
      - 'type:ci'
      - 'type:refactor'
      - 'type:test'
      - 'type:config'
