name: Jest coverage report for PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  jest-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Coverage"
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: failed-tests
          test-script: npm run test:coverage
