name: Verify labels in PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  label-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v3
        with:
          allowed_multiple: type:feature,
            type:style,
            type:test,
            type:bugfix,
            type:docs,
            type:refactor,
            type:perf,
            type:config,
            type:build,
            type:ci
